[build]
  publish = "Chemney_VR/VR Smoke School"

[[headers]]
  for = "/Build/VR Smoke School.wasm.br"
  [headers.values]
    "Content-Type" = "application/wasm"
    "Content-Encoding" = "br"

[[headers]]
  for = "/Build/VR Smoke School.framework.js.br"
  [headers.values]
    "Content-Type" = "application/javascript"
    "Content-Encoding" = "br"

[[headers]]
  for = "/Build/VR Smoke School.data.br"
  [headers.values]
    "Content-Type" = "application/octet-stream"
    "Content-Encoding" = "br"

[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    "Content-Type" = "application/wasm"
    "Content-Encoding" = "br"

[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
    "Content-Type" = "application/javascript"
    "Content-Encoding" = "br"

[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
    "Content-Type" = "application/octet-stream"
    "Content-Encoding" = "br"
